
# Tomcat Server
server:
  port: 8080

# Logger
logging.level:
  web: DEBUG
  '[com.simplilearn.estore]': DEBUG 
        
spring:
# Jackson Settings
  jackson:
    date-format: "yyyy-MM-dd" 
    
# Database Settings
  datasource: 
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        '[format_sql]': true
    open-in-view: true
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
           
---

# AWS Configuration    

server:
  port: 8082

spring:
  config:
    activate.on-profile: aws    

# Database Settings
  datasource:
    url: jdbc:mysql://simplilearn-rds.cdwugyoeo2fu.us-east-1.rds.amazonaws.com:3306/ecommerce
    username: admin
    password: admin123 