
# Tomcat Server
server:
  port: 8080

# Logger
logging.level:
  web: DEBUG
  '[com.simplilearn.estore]': DEBUG 
        
spring:
# Jackson Settings
  jackson:
    date-format: "yyyy-MM-dd" 
    
# Database Settings
  datasource: 
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: rootroot
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        '[format_sql]': true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true